# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Pierre Osselin
tagline:          Machine Learning
description:      Destroyer of Worlds
url:              https://pierreosselin.github.io
baseurl:
paginate:         5
name:             Pierre Osselin

twitter_name:     emidup
github_name:      PierreOsselin
linkedin_name:    EmilienDupont
