# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Pierre Osselin
tagline:          Machine Learning
description:
url:              https://pierreosselin.github.io
baseurl:
plugins:
  - jekyll-paginate
paginate:         5
name:             Pierre Osselin

twitter_name:     POsselin
github_name:      PierreOsselin
linkedin_name:    pierre-osselin-85176412b
