# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Pierre Osselin
tagline:          King in the North
description:      King in the North
url:              https://pierreosselin.github.io
baseurl:
paginate:         5
name:             Pierre Osselin

#twitter_name:     emidup
github_name:      PierreOsselin
#linkedin_name:    EmilienDupont
